apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: pesaimzb8-go-gitops
  description: This is GitOps manifest for pesaimzb8-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=pesaimzb8-go
    backstage.io/kubernetes-id: pesaimzb8-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: pesaimzb8-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:pesaimzb8-go
